-- Add a test list setting with possible values
INSERT INTO settings (
    setting_key, 
    setting_value, 
    setting_type, 
    category, 
    description, 
    is_sensitive, 
    is_system_setting, 
    validation_rules_json,
    possible_values,
    display_name,
    data_type,
    default_value,
    is_required,
    is_read_only,
    can_delete,
    is_active,
    created_by,
    created_on
) VALUES (
    'DefaultViewMode',
    'Grid',
    'List',
    'ProductDisplay',
    'Default view mode for product listings - Grid, List, or Card view',
    0,
    0,
    '{}',
    '["Grid", "List", "Card"]',
    'Default View Mode',
    'List',
    'Grid',
    1,
    0,
    1,
    1,
    'System',
    CURRENT_TIMESTAMP
);

-- Add another test list setting
INSERT INTO settings (
    setting_key, 
    setting_value, 
    setting_type, 
    category, 
    description, 
    is_sensitive, 
    is_system_setting, 
    validation_rules_json,
    possible_values,
    display_name,
    data_type,
    default_value,
    is_required,
    is_read_only,
    can_delete,
    is_active,
    created_by,
    created_on
) VALUES (
    'EmailNotificationFrequency',
    'Daily',
    'List',
    'Notification',
    'How often to send email notifications',
    0,
    0,
    '{}',
    '["Immediate", "Hourly", "Daily", "Weekly", "Never"]',
    'Email Notification Frequency',
    'List',
    'Daily',
    1,
    0,
    1,
    1,
    'System',
    CURRENT_TIMESTAMP
);
