# Theme Configuration
theme: minima
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Site settings
title: "TechWayFit License Management"
description: "Comprehensive Enterprise Software Licensing Platform"
url: "https://tyfweb.github.io"
baseurl: "/twf_license_management"

# GitHub settings
github:
  repository_url: "https://github.com/tyfweb/twf_license_management"

# Footer settings
footer_content: "Copyright &copy; 2025 TechWayFit. Licensed under the <a href=\"https://github.com/tyfweb/twf_license_management/blob/main/LICENSE\">MIT License</a>."

# Print settings (for PDF generation)
print_title: "TechWayFit License Management Documentation"
print_subtitle: "Complete System Guide and API Reference"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# For GitHub Pages compatibility
safe: true
incremental: false
gist:
  noscript: false

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - legacy-docs

# Navigation structure
nav_sort: case_insensitive

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
